### ISSUE TITLE
ISSUE: Fichier sql non valide

### ISSUE THREAD

**Issue by eguesbaya** [WildCodeSchool/orleans-php-202103-project-voyante#197]
J'ai fait un source de projet_voyance, et il n'y a aucune table dedans... Il y a peut-être un soucis au niveau de votre fichier SQL?

**Comment by glochlainn** [comment]
Alors il faut créer une database en local afin de ne pas avoir de conflit avec le fichier dump.sql, il faudrait indiquer qu'il faut créer une BDD avec le nom "projet_voyance" ou alors peut être faciliter le source de votre fichier SQL
